# File @generated by hack/generate-authors.sh. DO NOT EDIT.
# This file lists all contributors to the repository.
# See hack/generate-authors.sh to make modifications.

Priscilla Momodu <priscillamomodu@gmail.com>
Emmanuel Rex Onuh <rexfada@gmail.com>
